package com.looker.droidify.data.encryption

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Protects the app's encryption [Key] while it sits in storage.
 *
 * The key that repository passwords are encrypted with used to be written to the settings file as
 * plain bytes, right next to the passwords it opens, which left the encryption decorative: whoever
 * could read one could read the other. Wrapping means the stored form is itself encrypted, under a
 * key that never leaves the device.
 */
interface KeyWrapper {

    /** [key] in its stored form, or null when this device can't wrap at all (see [KeystoreKeyWrapper]). */
    fun wrap(key: Key): ByteArray?

    /** The key [wrapped] holds, or null when it can't be opened on this device: it was wrapped
     *  elsewhere, or the wrapping key is gone. */
    fun unwrap(wrapped: ByteArray): Key?
}

/**
 * Wraps the key under a second key held in Android's own key store, where it is generated and stays:
 * the platform hands out operations on it, never the key itself, and on most devices it lives in
 * dedicated hardware the OS can't read out either. So the wrapped form is worth nothing off the
 * device that wrote it, which is the point. A copy of the settings file, a backup, another phone:
 * none of them carry what opens it.
 *
 * Deliberately not tied to the user unlocking the device ([KeyGenParameterSpec.Builder] has options
 * for that): syncing a repository runs on a schedule, in the background, with the screen off, and a
 * key that refuses to work then would break exactly the feature this protects. A changed screen lock
 * therefore doesn't invalidate this key either.
 *
 * AES-GCM, so unwrapping a wrapped key that was altered fails outright instead of quietly yielding
 * different bytes.
 */
class KeystoreKeyWrapper(private val alias: String = DEFAULT_ALIAS) : KeyWrapper {

    override fun wrap(key: Key): ByteArray? = runCatching {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, wrappingKey())
        val iv = cipher.iv
        val body = cipher.doFinal(key.secretKey)
        // The IV is generated by the cipher and is needed to undo this, so it travels with the
        // result. Length-prefixed rather than assumed: GCM's usual 12 bytes is a convention, not a
        // guarantee every provider follows.
        byteArrayOf(iv.size.toByte()) + iv + body
    }.getOrNull()

    override fun unwrap(wrapped: ByteArray): Key? = runCatching {
        val ivSize = wrapped[0].toInt()
        val iv = wrapped.copyOfRange(1, 1 + ivSize)
        val body = wrapped.copyOfRange(1 + ivSize, wrapped.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, wrappingKey(), GCMParameterSpec(TAG_BITS, iv))
        Key(cipher.doFinal(body))
    }.getOrNull()

    /** This app's wrapping key, generated on first use and read back from the key store after that. */
    private fun wrappingKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEY_STORE).apply { load(null) }
        (keyStore.getKey(alias, null) as? SecretKey)?.let { return it }
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEY_STORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_BITS)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val DEFAULT_ALIAS = "omnify_credential_key"
        const val ANDROID_KEY_STORE = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val TAG_BITS = 128
        const val KEY_BITS = 256
    }
}
